[package]
name = "systemd-crontab-generator"
version = "0.9.0"
description = "Systemd generator for crontab files support"
readme = "README.md"
repository = "https://github.com/rust/systemd-crontab-generator"
license = "MIT"
authors = ["Konstantin Stepanov <me@kstep.me>"]

[dependencies]
md5 = "*"
log = "*"
cronparse = "*"
pgs-files = "*"
time = "*"
glob = "*"

[dependencies.kernlog]
version = "*"
features = ["nightly"]
path = "/home/kstep/git/rust/kernlog"
