[package]
name = "systemd-crontab-generator"
version = "0.9.0"
description = "Systemd generator for crontab files support"
readme = "README.md"
repository = "https://github.com/rust/systemd-crontab-generator"
license = "MIT"
authors = ["Konstantin Stepanov <me@kstep.me>"]
build = "build.rs"

[features]
default = ["sched-boot", "sched-hourly", "sched-daily", "sched-weekly", "sched-monthly"]

sched-boot = []
sched-hourly = []
sched-daily = []
sched-weekly = []
sched-monthly = []
sched-yearly = []
sched-minutely = []
sched-quarterly = []
sched-semi-annually = []
persistent = []

[build-dependencies]
rustc-serialize = "*"

[build-dependencies.rumblebars]
version = "*"
git = "https://github.com/nicolas-cherel/rumblebars.git"

[dependencies]
libc = "*"
md5 = "*"
log = "*"
cronparse = "*"
time = "*"
glob = "*"
docopt = "*"
rustc-serialize = "*"
tempfile = "*"
users = "*"

[dependencies.kernlog]
version = "*"
#path = "/home/kstep/git/rust/kernlog"
